DROP DATABASE IF EXISTS `z2w_chatroom`;
CREATE DATABASE IF NOT EXISTS z2w_chatroom;
USE z2w_chatroom;
CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `password_hash` TEXT NOT NULL,
    `salt` TEXT NOT NULL,
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (`username`),
    UNIQUE (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `room_info` (
    `room_id` VARCHAR(64) NOT NULL PRIMARY KEY,
    `room_name` VARCHAR(255) NOT NULL,
    `creator_id` BIGINT NOT NULL,
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_creator (`creator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

